# -*- coding: utf-8 -*-
"""study.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f42TNE9T_659C_pdwQdKng68IP7id6o_
"""

orders=["milk","Bread","Eggs"]
print(orders)

orders=["milk","Bread","Eggs"]
orders.append("Butter")
print(orders)

orders=["milk","Bread","Eggs"]
orders.insert(1, "fruit")
print(orders)

partner_orders=["rice","oil"]
orders.extend(partner_orders)
print(orders)